---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
    name: tanka-plugin
spec:
    version: v1.0
    generate:
        command:
            - bash
            - "-c"
            - "/script-wrapper /generate"

    init:
        command:
            - bash
            - "-c"
            - "/script-wrapper /init"

    discover:
        find:
            command:
                - "bash"
                - "-c"
                - "find . -name jsonnetfile.json"
