#!/bin/bash

set -ue

set -o pipefail

LOG_DIR=/tmp/argocd/$ARGOCD_APP_NAME/$ARGOCD_APP_REVISION

SCRIPT=$1

SCRIPT_NAME=$(basename "$SCRIPT")

mkdir -p "$LOG_DIR"

STDOUT="$LOG_DIR/$SCRIPT_NAME.stdout.log"
STDERR="$LOG_DIR/$SCRIPT_NAME.stderr.log"

# This method is extremely easy to implement and read and should be more than enough for a CMP. However, it destroys the
# order of stdout and stderr, so this needs to be fixed if the order is required (which it is not IIRC).

"$SCRIPT" 1> "$STDOUT" 2> "$STDERR"  

cat "$STDOUT"
cat "$STDERR" >&2
